apiVersion: batch/v1
kind: Job
metadata:
  name: sample
  namespace: dev
spec:
  template:
    spec:
      containers:
      - name: sample
        image: rkalluru/entry:v1
        args: ["google.com"]
      restartPolicy: Never
  backoffLimit: 4