- name: Check vars
  hosts: localhost
  vars:
    src: /etc/hosts
    dest: /tmp/hosts
    state: present
  tasks:
    - name: Copy Hosts 
      copy:
        src: "{{src}}"
        dest: "{{dest}}"
        state: "{{state}}"
