- name: Check vars
  hosts: localhost
  vars:
    src: /etc/hosts
    dest: /tmp/hosts
    mode: "0660"
  tasks:
    - name: Copy Hosts 
      copy:
        src: "{{src}}"
        dest: "{{dest}}"
        mode: "{{mode}}"
